language: ruby
rvm:
  - 2.6.1
services:
  - docker
install:
  - cp .env.example .env
  - make build
  - ls -la
  - ls -la tmp
  - sudo chown -R travis:travis .
  - sudo chmod 777 -R .
script:
  - make tests
